### ISSUE TITLE
Roadmap for 1.0

### ISSUE THREAD

**Issue by codekirei** [codekirei/sentaku#1]
Here's what I would like to add before slapping a `1.0` on this:
- [ ] More verbose error handling -- maybe?
- [ ] Tests
- [ ] Travis integration (service hook, readme badge, etc.)
- [ ] Readme swag ( shields.io/badge.fury.io/coveralls.io/david-dm.org )
